### ISSUE TITLE
Not an issue — just a question

### ISSUE THREAD

**Issue by VOC-LINK** [nihirash/Agon-CPM2.2#14]
Hello,
sorry that I post this in „issues” but it seems it's the only place I can contact you.

Just two short questions:
1) Is it possible, using your CPM variant, to access Agon's GPIO lines?
2) Is it possible to use Agon's graphics (and maybe even sound) under CP/M?

Re 2) — I'm aware CP/M never was „multimedial thing”, but actually why not use graphics/sound with Agon-specific variant, if only there is a way to add some kind of „hooks” in CP/M's API, that won't ruin compatibility with old software?

**Comment by nihirash** [comment]
1. Same assembly code that works for GPIO in MOS mode will work with GPIO in CP/M mode. 

There shouldn't be issues. I think. 

2. Currently, CP/M working in terminal mode of VDP(where Agon-specific extensions are disabled). 

But! You still have access to fabGL terminal's graphical extensions - so you can use special control codes for graphics. 

You can get some info about them [here](http://www.fabglib.org/special_term_escapes.html)

**Comment by VOC-LINK** [comment]
Thank you very much for your prompt response!
One more question: you've decided to port CP/M 2.2 for Agon. Does it mean porting 3.0 may not be possible for some reason?

**Comment by nihirash** [comment]
CP/M 3.0 isn't impossible on Agon Light but it won't be very useful(less TPA, not big real profit from CP/M 3.0 itself - 99,99% of software aimed to CP/M 2.2).

eZ80 haven't Z180 MMU(I might be wrong - I'll check it and say more clearly) paging and pages only by full 64K pages in legacy mode. If it have Z180 MMU mode - there will be reason for CP/M 3.0.

**Comment by VOC-LINK** [comment]
Thanks again! And a suggestion: maybe it would be good idea to convert CP/M to ADL 24-bit mode of eZ80? And — at the same time — to cure its shortcomings, like lack of „internalization”, lack of the real filesystem (at least FAT32 would be handy), lack of graphics etc… you know: there's an opportunity to set a new standard. :)

**Comment by nihirash** [comment]
Agon's MOS can be used as 24 bit equivalent for CP/M 😄 

I think best way will be implement some compatibility layer for MOS and proxify FS calls to FatFS and console calls to some terminal emulation layer.
