### ISSUE TITLE
Where can I find cpm.bin?

### ISSUE THREAD

**Issue by Andre4sH1** [nihirash/Agon-CPM2.2#16]
I can't find cpm.bin in the repo or should I build it myself? How do I do to build it if that is the case.

**Comment by theflynn49** [comment]
It should be there : `https://github.com/nihirash/Agon-CPM2.2/releases`

**Comment by Andre4sH1** [comment]
Thanks! was just looking in the repo.

**Comment by nihirash** [comment]
Hello!

Thank you @theflynn49 for answering on question!

If there will be some issues - please reopen issue!
