### ISSUE TITLE
Enhancement: Support all 15 drives in CP/M via drive images

### ISSUE THREAD

**Issue by snakebyte69** [nihirash/Agon-CPM2.2#3]
"The Select Disk function designates the disk drive named in register E as the default disk for subsequent file operations, with E = 0 for drive A, 1 for drive B, and so on through 15, corresponding to drive P in a full 16 drive system."
Can we have more drives please A: to Z:
A: to P: if you want to be CP/M 2.2 Specific

**Comment by nihirash** [comment]
Making support for A to Z ins't possible without breaking internal logic of BDOS. 

A to P is possible(with TPA area decreasing cause we'll need add more allocation vectors that will be accessible from BDOS) but need a bit more changes in drive emulation routines and requires some research.

**Comment by nihirash** [comment]
Implemented 😄

**Comment by nihirash** [comment]
CP/M broken with current MOS

**Comment by nihirash** [comment]
Will be fixed with update of MOS: https://github.com/breakintoprogram/agon-mos/pull/70

**Comment by nihirash** [comment]
Release version fixed it!
