### ISSUE TITLE
Feature Request: Fonts, Font Size, Resolution, Terminal Emulation

### ISSUE THREAD

**Issue by snakebyte69** [nihirash/Agon-CPM2.2#4]
Settings to set the font and colour that will be used by CP/M
Terminal Emulation
CP/M Utility to change resolutions and fonts.

A resolution and font could be saved like this
Televideo 950 - TV950.trm and loaded on startup.

**Comment by nihirash** [comment]
This task more about VDP behavior enhancement. 

Terminal class can switch between terminal emulation modes but it isn't exposed to ESC-codes. It's better implement on VDP side cause it already have support of several terminal types. 

When it will be done - there will be required very small and simple CP/M application that will cover mode switching.

Implementing in code terminal emulation isn't first requirements task for current project. Current emulation covers all requirements and almost all software have configuration options.
