### ISSUE TITLE
Bug: C: Drive - C character changes

### ISSUE THREAD

**Issue by snakebyte69** [nihirash/Agon-CPM2.2#5]
After changing to C: the 'C' changes to a weird X character
A:, B: and D: don't do this.

**Comment by nihirash** [comment]
Can't reproduce at all.

**Comment by snakebyte69** [comment]
hmm...
I'll make a video and sent it to you.
I'll try it on another Agon Light also

**Comment by nihirash** [comment]
Closed cause I can't reproduce at all.
