### ISSUE TITLE
Keyboard not working with VDP version 1.03RC3

### ISSUE THREAD

**Issue by tofro** [nihirash/Agon-CPM2.2#6]
On Agon light with newest firmware, CP/M starts up and shows its banner, but doesn't react to keyboard input.

**Comment by nihirash** [comment]
What version of VDP?

**Comment by tofro** [comment]
1.03 RC3. Im using
SET KEYBOARD 2, not sure if this would make a difference.

**Comment by nihirash** [comment]
I'll update and check. 

I'm on just 1.03 and everything is fine. Looks like VDP issue but I'll check it.

**Comment by tofro** [comment]
Need to apologize:

Apparently, I had a mushy MOS version on my board - Upgraded to official 1.03 and everything seems to work. You can consider this issue closed.

**Comment by nihirash** [comment]
All fine! Thank you for testing :-)

**Comment by nihirash** [comment]
Tested with 1.04RC1 - everything is fine!
