### ISSUE TITLE
eZ80 memory read/write out of bounds in the agon emulator

### ISSUE THREAD

**Issue by guidol70** [nihirash/Agon-CPM2.2#7]
When I do try to start CPM 2.2 on the [agon emulator](https://github.com/astralaster/agon-light-emulator) with
*load cpm.bin
*run
I do get many 
**eZ80 memory read/write out of bounds** 
messages in the Debug-Log Window

Please see attached .txt file
[emulator_memory_error.txt](https://github.com/nihirash/Agon-CPM2.2/files/11645293/emulator_memory_error.txt)

**Comment by nihirash** [comment]
It's emulation issue.
Possibly wrong prefixed commands execution
