### ISSUE TITLE
"ed" quits immediately

### ISSUE THREAD

**Issue by joelburton** [nihirash/Agon-CPM2.2#9]
I imagine this might fall under the "some terminal things may not work" caveat, but, if in case its useful feedback: ed (on disk #2) quits, either when you try to edit a new file or an existing file.

**Comment by nihirash** [comment]
I'll check this on weekend - but it should work. 

I didn't checked ED but created a lot files with TE and WordStar.

**Comment by nihirash** [comment]
I've grab official ED binary from here: http://www.cpm.z80.de/download/cpm22-b.zip

[And it works ok as I understand. ](https://www.youtube.com/watch?v=EmDw6F9szIE)

I've tried use it from drive B without any issues. 

But it's important run ED with filename. It won't work without filename not only in our CP/M 2.2 implementation but everywhere.

**Comment by joelburton** [comment]
Thanks, @nihirash .

It works for me, too, if I grab a copy of "ed" from there.

However, what doesn't work is the "ed" provided in cpmb.dsk --- that one silently fails. (And comparing them, the copy of "ed" on "cpmb.dsk" is a few bytes smaller)

I appreciate your trying this out!

**Comment by nihirash** [comment]
Sorry for that - for initial images I’ve used RC2014 files some of them are broken. 

A bit little later I’ll prepare better images for start using CP/M.
